name:                renum-files
version:             0.1.0.0
github:              "gfngfn/renum-files"
license:             BSD3
author:              "gfngfn"
maintainer:          "b d . g f n g f n <at> g m a i l . c o m"
copyright:           "2018-2020 gfngfn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/renum-files#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- text
- attoparsec
- aeson
- unordered-containers
- scientific
- bytestring
- containers
- split

library:
  source-dirs: src

executables:
  renum-files-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - renum-files

tests:
  renum-files-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - renum-files
    - HUnit
